"""empty message

Revision ID: 4ee18d0b8a6f
Revises: 6abdb121c908
Create Date: 2018-09-11 15:30:37.490283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ee18d0b8a6f'
down_revision = '6abdb121c908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bin', sa.Column('depth', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bin', 'depth')
    # ### end Alembic commands ###
