"""empty message

Revision ID: 6abdb121c908
Revises: 84dd72554e5d
Create Date: 2018-09-10 12:23:22.554265

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6abdb121c908'
down_revision = '84dd72554e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('access_ibfk_1', 'access', type_='foreignkey')
    op.drop_column('access', 'feature_id')
    op.add_column('bin', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.drop_constraint('bin_ibfk_1', 'bin', type_='foreignkey')
    op.create_foreign_key(None, 'bin', 'warehouse', ['warehouse_id'], ['id'])
    op.drop_column('bin', 'location_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bin', sa.Column('location_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bin', type_='foreignkey')
    op.create_foreign_key('bin_ibfk_1', 'bin', 'location', ['location_id'], ['id'])
    op.drop_column('bin', 'warehouse_id')
    op.add_column('access', sa.Column('feature_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('access_ibfk_1', 'access', 'feature', ['feature_id'], ['id'])
    # ### end Alembic commands ###
